[project]
name = "odoo-bringout-eurooffice-eurooffice_odoo_oca_dms"
version = "16.0.1.0.0"
description = "Euro-Office/Euro-Office integration with OCA DMS (open source alternative to Odoo Enterprise Documents)"
authors = [
    { name = "Ernad Husremovic", email = "hernad@bring.out.ba" }
]
dependencies = [
    "pyjwt>=2.0.0"
]
readme = "README.md"
requires-python = ">= 3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python :: 3",
    "Topic :: Office/Business",
]

[project.urls]
homepage = "https://www.bring.out.ba"
repository = "https://github.com/bringout/0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["eurooffice_odoo_oca_dms"]
